#####################
# Кастомные свойства
#####################

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Свойство EMAIL.
  Local\Bitrix\CustomProperties\Email:
    arguments: ['@Local\Services\Validation\Custom\CustomEmailValidatorNullable']
    tags:
      - { name: bitrix.property.type }

  # Свойство PHONE.
  Local\Bitrix\CustomProperties\Phone:
    arguments: ['@Local\Services\Validation\Custom\LaravelPhoneValidatorNullable']
    tags:
      - { name: bitrix.property.type }

  # Свойство YoutubeVideo.
  Local\Bitrix\CustomProperties\YoutubeVideo:
    tags:
      - { name: bitrix.property.type }

  Local\Bitrix\CustomProperties\YesNoType:
    tags:
      - { name: bitrix.property.type }

  Local\Bitrix\CustomProperties\BitrixFormType:
    tags:
      - { name: bitrix.property.type }